// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC98SFIkI1M2peLHyM_LYYQX6pc5eG8rOc',
    appId: '1:1026058589110:web:8659b279178ca3b50fa717',
    messagingSenderId: '1026058589110',
    projectId: 'market-research-24aa6',
    authDomain: 'market-research-24aa6.firebaseapp.com',
    storageBucket: 'market-research-24aa6.firebasestorage.app',
    measurementId: 'G-DZ1TJV9PY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3CfM9948zGshsR1KmSAcb-2Ub2WOIr-8',
    appId: '1:1026058589110:android:5cb07303face47620fa717',
    messagingSenderId: '1026058589110',
    projectId: 'market-research-24aa6',
    storageBucket: 'market-research-24aa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3CfM9948zGshsR1KmSAcb-2Ub2WOIr-8',
    appId: '1:1026058589110:ios:5cb07303face47620fa717',
    messagingSenderId: '1026058589110',
    projectId: 'market-research-24aa6',
    storageBucket: 'market-research-24aa6.firebasestorage.app',
    iosBundleId: 'com.marketresearch.market_research',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3CfM9948zGshsR1KmSAcb-2Ub2WOIr-8',
    appId: '1:1026058589110:ios:5cb07303face47620fa717',
    messagingSenderId: '1026058589110',
    projectId: 'market-research-24aa6',
    storageBucket: 'market-research-24aa6.firebasestorage.app',
    iosBundleId: 'com.marketresearch.market_research',
  );
}
